function [figure1] = createfigure(X1, Y1, name)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data

%  Auto-generated by MATLAB on 27-Oct-2025 13:35:29

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName',name,'Marker','x');

% Create ylabel
ylabel({'c'});

% Create xlabel
xlabel({'x'});

% Create title
title({''});

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',12,'XGrid','on','YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.150595244694323 0.842460318702081 0.478571417023029 0.0547619034137045]);

